Repository google/libsxg, pull requests merged in 2019-11, with the labels that each got.

#12 add integrity mode
  docs/gensxg.md
  src/gensxg.c
Labels: enhancement

#15 fix typo: s/Emty/Empty/
  docs/sxg_signer_list.md
Labels: documentation, invalid

#16 Prefer casting to const data, not const pointer
  tests/sxg_codec_test.cc
Labels: cla: yes

#17 Include PEM headers in example
  README.md
Labels: cla: yes

#18 Correct typos in docs
  docs/gensxg.md
  docs/sxg_buffer.md
  docs/sxg_generate.md
  docs/sxg_signer_list.md
Labels: cla: yes

#19 Add test common library
  CMakeLists.txt
  tests/nfail_malloc_test.cc
  tests/sxg_buffer_test.cc
  tests/sxg_codec_test.cc
  tests/sxg_encoded_response_test.cc
  tests/sxg_generate_test.cc
  tests/sxg_header_test.cc
  tests/sxg_sig_test.cc
  tests/sxg_signer_list_test.cc
  tests/test_util.cc
  tests/test_util.h
  tests/toplevel_test.cc
Labels: cla: yes

#22 rename OVERVIEW.md to index.md for github pages
  docs/index.md
Labels: cla: yes, documentation

#24 Fix typo in error message
  src/gensxg.c
Labels: cla: yes

#26 test_util.h order of includes
  tests/test_util.h
Labels: cla: yes

#27 remove extra blank line
  fuzzers/signer_fuzzer.cc
Labels: cla: yes

#25 follow the change of document filename
  README.md
Labels: cla: yes

#28 add missing include header
  src/sxg_header.c
Labels: cla: yes

#29 add missing header
  src/sxg_signer_list.c
Labels: cla: yes

#30 remove unrequired spaces
  tests/test_util.cc
Labels: cla: yes
